### ISSUE TITLE
Does not cooperate with IPython 0.11

### ISSUE THREAD

**Issue by lrem** [flavioamieiro/nose-ipdb#5]
Current version of the plugin does not work with current version of IPython (0.11). It works in the same setup with the previous version (0.10.1). Relevant tracebacks:

```
 - TRACEBACK --------------------------------------------------------------------
 Traceback (most recent call last):
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/case.py", line 133, in run
     self.runTest(result)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
     test(result)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/case.py", line 391, in __call__
     return self.run(*args, **kwds)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/case.py", line 331, in run
     result.addFailure(self, sys.exc_info())
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/proxy.py", line 149, in addFailure
     plugins.addFailure(self.test, err)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/plugins/manager.py", line 94, in __call__
     return self.call(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/plugins/manager.py", line 162, in simple
     result = meth(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/ipdbplugin.py", line 55, in addFailure
     self.debug(err)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/ipdbplugin.py", line 65, in debug
     shell = IPython.Shell.IPShell(argv=[''])
 AttributeError: 'module' object has no attribute 'Shell'
 --------------------------------------------------------------------------------
 Traceback (most recent call last):
   File "/usr/local/share/python/nosetests", line 9, in <module>
     load_entry_point('nose==1.1.2', 'console_scripts', 'nosetests')()
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/core.py", line 118, in __init__
     **extra_args)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/main.py", line 95, in __init__
     self.runTests()
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/core.py", line 197, in runTests
     result = self.testRunner.run(self.test)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/core.py", line 61, in run
     test(result)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
     return self.run(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 223, in run
     test(orig)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/suite.py", line 70, in __call__
     return self.run(*args, **kwds)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 74, in run
     test(result)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
     return self.run(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 223, in run
     test(orig)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
     return self.run(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 223, in run
     test(orig)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
     return self.run(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 223, in run
     test(orig)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
     return self.run(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/suite.py", line 223, in run
     test(orig)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
     return self.run(*arg, **kwarg)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/case.py", line 138, in run
     result.addError(self, err)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/proxy.py", line 134, in addError
     plugins.addError(self.test, err)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/plugins/manager.py", line 94, in __call__
     return self.call(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nose/plugins/manager.py", line 162, in simple
     result = meth(*arg, **kw)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/ipdbplugin.py", line 48, in addError
     self.debug(err)
   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/ipdbplugin.py", line 65, in debug
     shell = IPython.Shell.IPShell(argv=[''])
 AttributeError: 'module' object has no attribute 'Shell'
```
